const users = require('./users/users.service.js')
const companies = require('./companies/companies.service.js')
const authManagement = require('./auth-management/auth-management.service.js')
const boards = require('./boards/boards.service.js')
const companyManagement = require('./company-management/company-management.service.js')
const boardManagement = require('./board-management/board-management.service.js')
const emails = require('./emails/emails.service.js')
const invitations = require('./invitations/invitations.service.js')
const actions = require('./actions/actions.service.js')
const permissions = require('./permissions/permissions.service.js')
const credentials = require('./credentials/credentials.service.js')
const ideas = require('./ideas/ideas.service.js')
const uploads = require('./uploads/uploads.service.js')
const comments = require('./comments/comments.service.js')
const commentVotes = require('./comment-votes/comment-votes.service.js')
const ideaVotes = require('./idea-votes/idea-votes.service.js')
const votes = require('./votes/votes.service.js')
const slackIntegration = require('./slack-integration/slack-integration.service.js')
const inviteBoard = require('./invite-board/invite-board.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users)
  app.configure(companies)
  app.configure(authManagement)
  app.configure(boards)
  app.configure(companyManagement)
  app.configure(boardManagement)
  app.configure(emails)
  app.configure(invitations)
  app.configure(actions)
  app.configure(permissions)
  app.configure(credentials)
  app.configure(ideas)
  app.configure(uploads)
  app.configure(comments)
  app.configure(commentVotes)
  app.configure(ideaVotes)
  app.configure(votes)
  app.configure(slackIntegration)
  app.configure(inviteBoard);
}
